### PR TITLE
Update rubocop

### PR DESCRIPTION
**Pull request by tjchambers**

### CODE REVIEW

**Comment by benjaminwood** [comment]
But where are the specs? :trollface:

**Comment by tjchambers** [comment]
@benjaminwood good question. But I had to run rubocop on this repo to discover the repo had the wrong style namespace.

**Comment by tjchambers** [comment]
BTW as an aside the gemspec has a utf-8 declaration that rubocop says is unnecessary. I am not sure, but given the target for this repo in terms of Ruby versions I think I concur. Maybe @nvick wants to fix?

**Comment by nvick** [comment]
Interesting 0.49.1 did not call that out but when I updated 0.50.0 did. I'll fix it.

**Pull request merged**
